### ISSUE TITLE
Build client after a Galaxy update

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/ansible-galaxy#86]
We switch our target branch ("a fork of the dev").

It raised an error during the client building:

```
TASK [galaxyproject.galaxy : Install yarn] *************************************
ok: [192.168.105.118]

TASK [galaxyproject.galaxy : Build client] *************************************
fatal: [192.168.105.118]: FAILED! => {"changed": false, "cmd": "/usr/bin/gmake client-production-maps", "msg": "", "rc": 2, "stderr": "error eslint@6.4.0: The engine \"node\" is incompatible with this module. Expected version \"^8.10.0 || ^10.13.0 || >=11.10.1\". Got \"9.11.1\"\nerror Found incompatible module.\ngmake: *** [node-deps] Erreur 1\n", "stderr_lines": ["error eslint@6.4.0: The engine \"node\" is incompatible with this module. Expected version \"^8.10.0 || ^10.13.0 || >=11.10.1\". Got \"9.11.1\"", "error Found incompatible module.", "gmake: *** [node-deps] Erreur 1"], "stdout": "cd client && yarn install --network-timeout 300000 --check-files\nyarn install v1.17.3\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo fsevents@1.2.4: The platform \"linux\" is incompatible with this module.\ninfo \"fsevents@1.2.4\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n", "stdout_lines": ["cd client && yarn install --network-timeout 300000 --check-files", "yarn install v1.17.3", "[1/4] Resolving packages...", "[2/4] Fetching packages...", "info fsevents@1.2.4: The platform \"linux\" is incompatible with this module.", "info \"fsevents@1.2.4\" is an optional dependency and failed compatibility check. Excluding it from installation.", "info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command."]
```

I have to update the Galaxy dependencies using:
```
(.venv) [root@galaxy-dev server]# ./scripts/common_startup.sh --no-create-venv
```
Maybe there was another way to update node?

Should [tasks/client.yml](https://github.com/galaxyproject/ansible-galaxy/blob/master/tasks/client.yml#L3) block include [tasks/dependencies.yml](https://github.com/galaxyproject/ansible-galaxy/blob/master/tasks/dependencies.yml)

**Comment by dannon** [comment]
Hrmm, I thought this should be handled by `_inc_node_version` here: https://github.com/galaxyproject/ansible-galaxy/blob/master/tasks/client.yml#L49

If you wanted to try to debug, for what it's worth, right now in the base Galaxy startup scripts this is handled at:  https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh#L224

**Comment by lecorguille** [comment]
I lost the trace, I relaunch the CI job and that overwrite the ansible logs :/

But manually, it works perfectely (with a couple of error and warning)
```
$ ./scripts/common_startup.sh --no-create-venv
[...]
The Galaxy client is out of date and will be built now.
Installing node into /shared/mfs/data/dev/galaxy/.venv with nodeenv.
 * Install prebuilt node (10.15.3) ..... done.
[...]
```

Here are the errors and warnings I got, surely not related to our issue.
And note, that the client seems up:
```
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @handsontable/vue@2.0.0" has incorrect peer dependency "handsontable@^4.0.0".
warning " > eslint-plugin-vue@5.2.3" has incorrect peer dependency "eslint@^5.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@5.0.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] Building fresh packages...
Done in 525.80s.
yarn run v1.17.3
$ NODE_ENV=production gulp && yarn run webpack-production-maps && yarn run save-build-hash
[11:43:29] Using gulpfile /shared/mfs/data/dev/galaxy/server/client/gulpfile.js
[11:43:29] Starting 'default'...
[11:43:29] Starting 'stageLibs'...
[11:43:29] Starting 'fonts'...
[11:43:29] Finished 'stageLibs' after 50 ms
[11:43:29] Starting 'cleanPlugins'...
[11:43:34] Finished 'cleanPlugins' after 4.41 s
[11:43:34] Starting 'buildPlugins'...
[11:43:34] Finished 'buildPlugins' after 2.35 ms
[11:43:34] Starting 'stagePlugins'...
Building  /shared/mfs/data/dev/galaxy/server/config/plugins/visualizations/annotate_image/
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ parcel build src/script.js -d static --no-source-maps
✨  Built in 237.75s.

static/script.js    349.46 KB    124.94s
Building  /shared/mfs/data/dev/galaxy/server/config/plugins/visualizations/openlayers/
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ parcel build src/script.js -d static --no-source-maps
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-07T10_09_10_893Z-debug.log
⚠️  Could not infer babel version. Defaulting to babel 7. Please add either babel-core or @babel/core as a dependency.
⚠️  Could not infer babel version. Defaulting to babel 7. Please add either babel-core or @babel/core as a dependency.
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-07T10_09_33_937Z-debug.log
🚨  /shared/mfs/data/dev/galaxy/server/config/plugins/visualizations/openlayers/node_modules/wkt-parser/index.js: Failed to install @babel/core.
    at PromiseQueue.install [as process] (/shared/mfs/data/dev/galaxy/server/config/plugins/visualizations/openlayers/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[12:09:34] Finished 'fonts' after 26 min
[12:09:37] Finished 'stagePlugins' after 26 min
[12:09:37] Finished 'default' after 26 min
$ GXY_BUILD_SOURCEMAPS=1 webpack -p
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[BABEL] Note: The code generator has deoptimised the styling of /shared/mfs/data/dev/galaxy/server/client/node_modules/handsontable/dist/handsontable.js as it exceeds the max of 500KB.
Hash: f620ec3a43b2d1e1b86b
Version: webpack 4.29.6
Time: 173097ms
Built at: 10/07/2019 12:12:49 PM
```

**Comment by natefoo** [comment]
Possibly too late now but the thing to check would've been whether the role upgraded your node version properly.

**Comment by nsoranzo** [comment]
xref. https://github.com/galaxyproject/ansible-galaxy/issues/107
